### ISSUE TITLE
Dashboard issues and permanent reloading on applying config

### ISSUE THREAD

**Issue by adrian-stephens** [flaviostutz/freepbx#14] opened 2020-07-25 08:39 UTC
flaviostutz/freepbx (no tag) pulled 2020-07-24
Freepbx 15.0.16.68

Issues:
	1. Dashboard reports ".htaccess files are disable on this webserver. Please enable them"
	2. Mail Queue reports (on dashboard) "unknown output from exim..."
	3. There is no ability to configure email
	4. FreePBX statistics panel on dashboard does not show hourly asterisk stats
        5. Applying a change to config leaves "reloading" dialog with bar at 100% permanently on screen.

**Comment by lukaneco** [comment] 2020-08-19 05:56
### i solve this problem doing the followiing steps:

we need to go to the cli of the docker or do a exec
https://linuxhandbook.com/run-docker-container/

`docker exec -it container_ID_or_name /bin/bash`

or pressing the next button (only with the docker desktop)
![image](https://user-images.githubusercontent.com/32082555/90597241-124d0380-e1c7-11ea-9498-3c2ba32a5f0d.png)


modify de apache2.conf to change the AllowOverride property below `<Directory "/var/www/html">`

from:    `AllowOverride None` -> To ->    `AllowOverride All`

you can do this using the next command

i prefer to do this with nano because i dont understand vim
```
apt-get update
apt-get install nano
```

`nano /etc/apache2/apache2.conf`

after modify this you must need to restart the apache2 server

`service apache2  restart`


if you dont found the apache2.conf you can run the next code to find it
`grep -R AllowOverride * | grep -v :# | grep -v available`

Source:
[https://www.voip-info.org/forum/threads/htaccess-files-are-disable-on-this-webserver-please-enable.17334/](https://www.voip-info.org/forum/threads/htaccess-files-are-disable-on-this-webserver-please-enable.17334/)

[https://community.freepbx.org/t/htaccess-files-are-disabled-on-this-webserver-what-verifications-does-freepbx-for-this/36456/3](https://community.freepbx.org/t/htaccess-files-are-disabled-on-this-webserver-what-verifications-does-freepbx-for-this/36456/3)

**Comment by flaviostutz** [comment] 2020-08-19 21:12
This is great! Would you mind sending a PR with those chances so that we can embedded your solution to the provided container image?
It would be great!

**Comment by flaviostutz** [comment] 2020-09-03 20:53
Duplicate of #17

**Comment by flaviostutz** [comment] 2020-09-03 22:36
@sumonchai/@adrian-stephens, thanks for the code snippets. I've just created a new image with the fixes you pointed out!
They are present in version flaviostutz/freepbx:15.0.16.8

**Closed by flaviostutz** 2020-09-03 22:36 UTC
