### ISSUE TITLE
Freepbx New ver. Need AllowOverride All

### ISSUE THREAD

**Issue by sumonchai** [flaviostutz/freepbx#17] opened 2020-08-24 10:09 UTC
I'm run command 
sed -i '/<Directory \/var\/www\/>/,/<\/Directory>/ s/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf

Freepbx fixed.

**Comment by flaviostutz** [comment] 2020-08-25 22:39
Which version of FreePbX did you tested this fix against?

**Comment by flaviostutz** [comment] 2020-09-03 20:54
I will work on that today...

Duplicate of #14.

**Closed** 2020-09-03 20:54 UTC

**Comment by flaviostutz** [comment] 2020-09-03 22:36
Please the latest image with this code snippet you sent at flaviostutz/freepbx:15.0.16.8
